### PR TITLE
adding `REFRESH-INTERVAL` property

### PR DESCRIPTION
**Pull request by ccoenen**
When parsing a nextcloud exported ics file, the parser would fail with this:

    ParsingError: Invalid Property 'REFRESH-INTERVAL'

I added the property to constants and parser, and also added a test including a nextcloud-exported fixture.

I was not sure where to put the fixture, so I created a new directory in fixtures. I would be happy to move it to a more appropriate place.

### CODE REVIEW

**Comment by iammatis** [comment]
Hey, thank you for the interest in the project and for the MR! According to [RFC 7986](https://datatracker.ietf.org/doc/html/rfc7986#section-5.7) property `REFRESH-INTERVAL` is of value `DURATION`, wouldn't it therefore be better parsed by the `DurationParser` and not the `StringParser` ? If so please change it. Regarding the fixture placement, let's create a new folder `calendar` and put it there ? Other than that, looks good :+1:

**Comment by ccoenen** [comment]
good catch! I updated the branch to include both suggestions. Thanks for the quick response :-)

**Comment by iammatis** [comment]
I changed the branch to `develop` from `master`, one last change-please squash the commits, then I will add you as a contributor and do the release :slightly_smiling_face:

**Comment by ccoenen** [comment]
It's not something I use, but I just noticed, that re-building the thing I just parsed (for example in the test), will not result in the same ical output. Some elements shift around, that's OK. But also, the `X-` properties and the `REFRESH-INTERVAL` are lost. I think I'll look for adding at least the `REFRESH-INTERVAL`.

**Comment by ccoenen** [comment]
I added the `REFRESH-INTERVAL` to the builder as well. This is currently a seperate commit. Please let me know if you want this addition, or if it's not something you want in there. If wou wish, I'll squash the two commits.

Also, I compared original vs. built, and as mentioned the `X-...` attributes are all gone.

```txt
 expect(received).toEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 0

    @@ -4,9 +4,6 @@
        "CALSCALE:GREGORIAN",
        "END:VCALENDAR",
        "PRODID:-//SabreDAV//SabreDAV//EN",
        "REFRESH-INTERVAL;VALUE=DURATION:PT4H",
        "VERSION:2.0",
    -   "X-APPLE-CALENDAR-COLOR:#31CC7C",
    -   "X-PUBLISHED-TTL:PT4H",
    -   "X-WR-CALNAME:default",
```
(note: I `split('\n').sort()`'ed the lines so that their order does not screw up the diff)


But adding those (if you want them) is probably another issue altogether.

**Comment by iammatis** [comment]
Oh yeah, I completely forgot about the builder, good job! Keep it here, but as you said squash it. Regarding the order of the elements, yeah they are built in certain order (always the same) so it is possible that it does not match exactly. I created an issue about the missing xProps in `VCALENDAR` component https://github.com/iammatis/iKalendar/issues/82, I'll get to it sometime during the week, but if you feel adventurous, feel free to submit another PR. Thanks, Matt

**Comment by iammatis** [comment]
Also please if you could add the `REFRESH-INTERVAL` into some builder test, so we have that covered too.

**Comment by ccoenen** [comment]
test now added to `simple_event.ics`

**Pull request merged**
